packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  bufferutil: true
  core-js: false
  es5-ext: false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
